api:
  base_url: "${LM_STUDIO_URL:-http://192.168.10.22:1234/v1}"
  model: "${LLM_MODEL:-openai/gpt-oss-120b}"
  timeout: 30
  max_retries: 3
  
processing:
  batch_size: 50
  checkpoint_every: 100
  
weights:
  cme: 0.6
  le: 0.4
  threshold: 0.7

database:
  path: "logs/api_logs.sqlite"