api:
  base_url: "${LM_STUDIO_URL:-http://192.168.10.22:1234/v1}"
  model: "${LLM_MODEL:-openai/gpt-oss-120b}"
  timeout: 30
  max_retries: 3
  temperature: 0.1
  max_tokens: 10000
  
prompts:
  system: "You are a forensic death investigation analyst specializing in intimate partner violence cases. Conduct systematic analysis through multiple phases: death classification, directionality assessment, suicide analysis, evidence hierarchy, temporal patterns, and quality control. Respond only with valid JSON."
  json_instruction: "Return ONLY valid JSON. No additional text, explanations, or formatting outside the JSON structure."
  
  # Simple template for basic compatibility
  unified_template: |
    Analyze this {narrative_type} narrative for intimate partner violence indicators.
    
    Look for ALL potential IPV indicators:
    
    Behavioral/Social: domestic violence history, current/former intimate partners, 
    restraining orders, stalking, jealousy, control, recent separation/breakup, 
    threats between partners, custody disputes, financial control.
    
    Physical/Medical: multiple injuries in various stages of healing, defensive wounds, 
    strangulation marks, pattern injuries consistent with objects, genital trauma, 
    history of prior unexplained injuries, injuries inconsistent with stated cause.
    
    Contextual: weapon belonging to partner, incident at shared residence, 
    witness accounts of relationship conflict, suicide notes mentioning partner.
    
    Narrative: '{narrative}'
    
    Respond with JSON:
    {{
      'ipv_detected': boolean,
      'confidence': 0-1,
      'indicators': [...],
      'rationale': '...'
    }}
  
  # Advanced forensic analysis template
  forensic_template: |
    Analyze this death investigation narrative for intimate partner violence (IPV).
    
    ANALYSIS TASKS:
    
    1. IPV DETECTION
    Identify ANY indicators of intimate partner violence:
    - Physical: injuries, strangulation, assault, defensive wounds
    - Sexual: forced acts, reproductive coercion
    - Psychological: threats, stalking, isolation, control
    - Economic: financial control, property damage
    - Weapons: firearm access/threats, weapon use
    
    2. DEATH ANALYSIS (if IPV present)
    - Death type: homicide/suicide/undetermined
    - Who died: victim/perpetrator/both
    - Primary aggressor: decedent/partner/mutual/unclear
    
    3. KEY EVIDENCE
    - Most critical evidence supporting IPV determination
    - Evidence quality: direct/indirect/circumstantial
    
    4. CASE SUMMARY
    - Brief factual summary of what happened
    - Your reasoning for IPV determination
    - Confidence level and why
    
    IMPORTANT:
    - Base analysis ONLY on explicit narrative content
    - List specific quotes/facts as evidence
    - If information is missing or unclear, state this
    - Consider alternative explanations
    
    Return ONLY this JSON structure:
    {
      "ipv_classification": {
        "ipv_present": boolean,
        "confidence": 0.0-1.0,
        "level": "definite|probable|possible|unlikely|none"
      },
      "indicators_found": {
        "physical": ["list specific indicators from text"],
        "psychological": ["list specific indicators"],
        "sexual": ["list specific indicators"],
        "economic": ["list specific indicators"],
        "weapons": ["list weapon-related indicators"]
      },
      "death_analysis": {
        "death_type": "homicide|suicide|homicide-suicide|undetermined|not_applicable",
        "decedent_role": "victim|perpetrator|both|unclear|not_applicable",
        "primary_aggressor": "decedent|partner|mutual|unclear|not_applicable",
        "confidence": 0.0-1.0
      },
      "critical_evidence": [
        {
          "evidence": "quote or fact from narrative",
          "type": "direct|indirect|circumstantial",
          "supports": "what this evidence indicates"
        }
      ],
      "case_summary": "2-3 sentence factual summary of the case",
      "reasoning": "Your analytical reasoning explaining why IPV is/isn't present and your confidence level",
      "data_quality": {
        "completeness": 0.0-1.0,
        "missing_info": ["what key information is missing"],
        "ambiguities": ["what remains unclear"]
      }
    }
  
processing:
  batch_size: 50
  checkpoint_every: 100
  use_forensic_analysis: true  # Enable advanced forensic mode
  max_narrative_tokens: 6000   # Max tokens for narrative input
  max_response_tokens: 4000    # Max tokens for LLM response
  forensic_prompt_file: "forensic_prompt.yml"  # Path to forensic prompt config
  
weights:
  cme: 0.6
  le: 0.4
  threshold: 0.5
  # Forensic analysis weights
  forensic_weights:
    physical_evidence: 0.9
    behavioral_evidence: 0.7
    contextual_evidence: 0.5
    circumstantial_evidence: 0.3
  # Confidence thresholds for forensic classifications
  forensic_thresholds:
    high_confidence: 0.8
    moderate_confidence: 0.6
    low_confidence: 0.4
    minimum_viable: 0.2

database:
  path: "logs/api_logs.sqlite"