# Optimized Evidence Weights - Based on forensic reliability patterns
weights:
  # Source weights for LE vs CME narratives
  cme: 0.65    # Increased: CME narratives often more objective, detailed
  le: 0.35     # Decreased: LE narratives more subjective, witness-dependent
  threshold: 0.6  # Lowered: Reduces false negatives for ambiguous cases
  
  # Dynamic evidence reliability scoring
  forensic_weights:
    # Physical evidence categories
    strangulation_marks: 0.95      # Highest: Almost never accidental
    defensive_wounds: 0.90         # Very high: Clear violence indicator
    pattern_injuries: 0.85         # High: Suggests weapon/object
    multiple_healing_stages: 0.88  # High: Indicates chronic violence
    sexual_assault_injuries: 0.92  # Very high: Often IPV-related
    
    # Behavioral evidence categories  
    restraining_orders: 0.85       # High: Legal documentation
    witness_threats: 0.80          # High: Third-party corroboration
    help_seeking: 0.75             # Good: Consistent with IPV patterns
    recent_separation: 0.70        # Moderate: High-risk period
    control_behaviors: 0.65        # Moderate: Need multiple indicators
    
    # Circumstantial evidence
    shared_residence: 0.50         # Moderate: Location matters
    weapon_ownership: 0.45         # Lower: Common, not IPV-specific
    suicide_note_partner: 0.60     # Moderate: Relationship context
    
  # Confidence thresholds for different decision points
  forensic_thresholds:
    definitive_ipv: 0.85          # High confidence IPV
    probable_ipv: 0.65            # Moderate confidence IPV  
    possible_ipv: 0.45            # Low confidence IPV
    insufficient_evidence: 0.25   # Below this = inconclusive
    
    # Quality control thresholds
    minimum_narrative_length: 50   # Characters needed for analysis
    maximum_contradiction_ratio: 0.3  # Contradictions vs total evidence
    required_physical_evidence_confidence: 0.8  # For homicide classification