# Optimized IPV Detection Configuration
# Version: 2.0 - Enhanced accuracy and reduced false negatives
# Key improvements: 3-tier evidence, better edge cases, dynamic reliability

api:
  base_url: "${LM_STUDIO_URL:-http://192.168.10.22:1234/v1}"
  model: "${LLM_MODEL:-openai/gpt-oss-120b}"
  timeout: 45  # Increased for complex reasoning
  max_retries: 3
  retry_delay: 2

processing:
  batch_size: 50
  checkpoint_every: 100
  chunk_size: 4000  # For long narratives
  
# Optimized weights based on CME forensic reliability
weights:
  cme: 0.65      # Higher weight for forensic evidence
  le: 0.35       # Lower weight for investigative reports
  threshold: 0.60  # Lowered to reduce false negatives
  confidence_floor: 0.40  # Minimum for uncertain cases

database:
  path: "logs/api_logs.sqlite"
  enable_wal: true

prompts:
  system: "You are an expert forensic analyst specializing in intimate partner violence detection in death investigations. Your task is to analyze death investigation narratives and determine if intimate partner violence (IPV) was involved. CRITICAL GUIDELINES: IPV includes violence by current/former romantic partners, spouses, dating partners. Look for BOTH explicit statements AND contextual patterns. Consider relationship dynamics, history, circumstances. When uncertain, err toward detecting potential IPV (false positive better than missed case). Focus on evidence strength rather than absolute certainty. Always respond with valid JSON following the exact format specified."
  
  json_instruction: "Return ONLY valid JSON. No additional text, explanations, or formatting outside the JSON structure."
  
  # Optimized unified template for both LE and CME narratives
  unified_template: |
    Analyze this death investigation narrative for intimate partner violence (IPV) indicators:

    NARRATIVE: "{narrative}"
    
    Use this 3-tier evidence analysis:

    **TIER 1 - DIRECT EVIDENCE** (Strongest indicators):
    - Explicit IPV statements ("killed by boyfriend", "domestic violence")
    - Witness accounts of partner violence
    - Prior domestic violence reports/arrests
    - Protective orders, restraining orders
    - Clear perpetrator-victim relationship statements

    **TIER 2 - CONTEXTUAL EVIDENCE** (Strong patterns):
    - Suspicious circumstances involving intimate partner
    - Partner present at scene with inconsistent story
    - History of relationship conflict/separation
    - Controlling behavior patterns described
    - Economic abuse or isolation mentioned

    **TIER 3 - CIRCUMSTANTIAL EVIDENCE** (Suggestive patterns):
    - Recent breakup/separation mentioned
    - Partner's emotional state (jealousy, anger)
    - Relationship stress factors
    - Victim's fear or concerns about partner
    - Stalking or harassment history

    **SPECIAL CONSIDERATIONS**:
    - Suicide cases: Check for partner coercion/manipulation
    - Overdose cases: Consider partner involvement in supply/pressure
    - "Accident" cases: Evaluate partner presence and explanation
    - Missing context: Note what's unclear rather than assuming negative

    **RELIABILITY FACTORS** (for dynamic scoring):
    - Source credibility: CME report vs. preliminary police report
    - Information completeness: detailed vs. sparse narrative
    - Corroborating evidence: multiple sources vs. single account
    - Temporal proximity: immediate vs. delayed reporting

    Respond with this EXACT JSON format:
    {{
      "ipv_detected": boolean,
      "confidence": float (0.0-1.0),
      "evidence_tier": "direct|contextual|circumstantial|none",
      "primary_indicators": ["indicator1", "indicator2", "indicator3"],
      "relationship_type": "current_partner|former_partner|spouse|ex_spouse|dating|unknown",
      "reliability_score": float (0.0-1.0),
      "key_evidence": "Brief quote or description of strongest evidence",
      "rationale": "Concise explanation of decision (2-3 sentences)",
      "uncertainty_factors": ["factor1", "factor2"] or null,
      "narrative_completeness": "complete|partial|minimal"
    }}


# Edge case handling patterns
edge_cases:
  suicide_with_partner_factors:
    description: "Suicide where partner involvement is suspected"
    indicators: ["partner_coercion", "recent_breakup", "financial_abuse", "threats_to_leave"]
    threshold_adjustment: -0.1  # Lower threshold for detection
    
  overdose_with_partner_present:
    description: "Drug overdose with intimate partner involvement"
    indicators: ["partner_supplied_drugs", "forced_consumption", "delayed_help_seeking"]
    threshold_adjustment: -0.1
    
  accident_with_inconsistencies:
    description: "Accidental death with partner present and inconsistent story"
    indicators: ["timeline_inconsistencies", "changing_story", "scene_inconsistencies"]
    threshold_adjustment: -0.15
    
  minimal_narrative:
    description: "Very brief narrative with limited information"
    indicators: ["insufficient_detail", "preliminary_report", "investigation_ongoing"]
    confidence_penalty: -0.2  # Reduce confidence but don't change detection

# Quality assurance settings
quality_control:
  min_narrative_length: 10  # Characters
  max_processing_time: 60   # Seconds per narrative
  require_json_validation: true
  log_parsing_errors: true
  
  # Confidence calibration
  confidence_bands:
    high: 0.80      # Strong evidence, clear case
    medium: 0.60    # Moderate evidence, likely case  
    low: 0.40       # Weak evidence, possible case
    uncertain: 0.20 # Minimal evidence, unlikely case

# Logging configuration
logging:
  level: "INFO"
  include_prompts: true
  include_responses: true
  track_performance: true
  
# Validation settings for testing
validation:
  enable_manual_comparison: true
  confusion_matrix_output: true
  false_negative_analysis: true
  confidence_calibration_plot: true
  
# Performance monitoring
monitoring:
  track_response_times: true
  monitor_api_errors: true
  log_confidence_distribution: true
  alert_on_high_error_rate: true
  error_rate_threshold: 0.05  # 5% error rate triggers alert