api:
  base_url: "${LM_STUDIO_URL:-http://192.168.10.22:1234/v1}"
  model: "${LLM_MODEL:-openai/gpt-oss-120b}"
  timeout: 30
  max_retries: 3
  temperature: 0.1
  max_tokens: 10000
  
prompts:
  system: "You are an expert at analyzing death investigation narratives for indicators of intimate partner violence. Respond only with valid JSON containing: ipv_detected (boolean), confidence (0-1), indicators (array), and rationale (string)."
  json_instruction: "Return ONLY valid JSON. No additional text or formatting."
  le_template: |
    Analyze this law enforcement narrative for intimate partner violence indicators.
    
    Look for: domestic violence, current/former partners, restraining orders, 
    jealousy, control, separation, threats between partners.
    
    Narrative: '{narrative}'
    
    Respond with JSON:
    {{
      'ipv_detected': boolean,
      'confidence': 0-1,
      'indicators': [...],
      'rationale': '...'
    }}
  cme_template: |
    Analyze this medical examiner narrative for intimate partner violence indicators.
    
    Look for: multiple injuries in various stages, defensive wounds, 
    strangulation, pattern injuries, history of prior injuries.
    
    Narrative: '{narrative}'
    
    Respond with JSON:
    {{
      'ipv_detected': boolean,
      'confidence': 0-1,
      'indicators': [...],
      'rationale': '...'
    }}
  
processing:
  batch_size: 50
  checkpoint_every: 100
  
weights:
  cme: 0.6
  le: 0.4
  threshold: 0.7

database:
  path: "logs/api_logs.sqlite"