# Minimal Configuration - No Bullshit Edition
# Everything that changes goes here. Nothing else.

api:
  url: ${LLM_API_URL:-http://localhost:1234/v1/chat/completions}
  model: ${LLM_MODEL:-gpt-4}
  
weights:
  le: 0.4
  cme: 0.6

threshold: 0.7

# That's it. 8 lines. Not 80.