<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaosong Zhang">
<meta name="author" content="Andrea Lynn Pangori">
<meta name="author" content="Anca Maria Tilea">
<meta name="dcterms.date" content="2025-12-15">
<meta name="keywords" content="intimate partner violence, natural language processing, large language models, NVDRS, death investigation, public health surveillance">

<title>Large Language Models for Detecting Intimate Partner Violence Indicators in NVDRS Suicide Narratives</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="manuscript_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="manuscript_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data Source</a>
  <ul class="collapse">
  <li><a href="#nvdrs-overview" id="toc-nvdrs-overview" class="nav-link" data-scroll-target="#nvdrs-overview">NVDRS Overview</a></li>
  <li><a href="#narrative-types" id="toc-narrative-types" class="nav-link" data-scroll-target="#narrative-types">Narrative Types</a></li>
  <li><a href="#study-dataset" id="toc-study-dataset" class="nav-link" data-scroll-target="#study-dataset">Study Dataset</a></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations">Ethical Considerations</a></li>
  </ul></li>
  <li><a href="#llm-classification-approach" id="toc-llm-classification-approach" class="nav-link" data-scroll-target="#llm-classification-approach">LLM Classification Approach</a>
  <ul class="collapse">
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#prompt-engineering" id="toc-prompt-engineering" class="nav-link" data-scroll-target="#prompt-engineering">Prompt Engineering</a></li>
  <li><a href="#temperature-parameter-optimization" id="toc-temperature-parameter-optimization" class="nav-link" data-scroll-target="#temperature-parameter-optimization">Temperature Parameter Optimization</a></li>
  </ul></li>
  <li><a href="#validation-methodology" id="toc-validation-methodology" class="nav-link" data-scroll-target="#validation-methodology">Validation Methodology</a>
  <ul class="collapse">
  <li><a href="#gold-standard-creation" id="toc-gold-standard-creation" class="nav-link" data-scroll-target="#gold-standard-creation">Gold Standard Creation</a></li>
  <li><a href="#inter-rater-reliability" id="toc-inter-rater-reliability" class="nav-link" data-scroll-target="#inter-rater-reliability">Inter-rater Reliability</a></li>
  <li><a href="#performance-metrics" id="toc-performance-metrics" class="nav-link" data-scroll-target="#performance-metrics">Performance Metrics</a></li>
  <li><a href="#experiment-framework" id="toc-experiment-framework" class="nav-link" data-scroll-target="#experiment-framework">Experiment Framework</a></li>
  </ul></li>
  <li><a href="#production-pipeline" id="toc-production-pipeline" class="nav-link" data-scroll-target="#production-pipeline">Production Pipeline</a>
  <ul class="collapse">
  <li><a href="#scalability-design" id="toc-scalability-design" class="nav-link" data-scroll-target="#scalability-design">Scalability Design</a></li>
  <li><a href="#quality-controls" id="toc-quality-controls" class="nav-link" data-scroll-target="#quality-controls">Quality Controls</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#production-scale-descriptive-results" id="toc-production-scale-descriptive-results" class="nav-link" data-scroll-target="#production-scale-descriptive-results">Production-Scale Descriptive Results</a>
  <ul class="collapse">
  <li><a href="#cohort-summary" id="toc-cohort-summary" class="nav-link" data-scroll-target="#cohort-summary">Cohort Summary</a></li>
  <li><a href="#production-run-operations" id="toc-production-run-operations" class="nav-link" data-scroll-target="#production-run-operations">Production Run Operations</a></li>
  <li><a href="#ipv-indicator-detection-rates-descriptive" id="toc-ipv-indicator-detection-rates-descriptive" class="nav-link" data-scroll-target="#ipv-indicator-detection-rates-descriptive">IPV Indicator Detection Rates (Descriptive)</a></li>
  <li><a href="#cme-le-agreement-analysis" id="toc-cme-le-agreement-analysis" class="nav-link" data-scroll-target="#cme-le-agreement-analysis">CME-LE Agreement Analysis</a></li>
  <li><a href="#confidence-score-analysis" id="toc-confidence-score-analysis" class="nav-link" data-scroll-target="#confidence-score-analysis">Confidence Score Analysis</a></li>
  </ul></li>
  <li><a href="#validated-performance-test-dataset" id="toc-validated-performance-test-dataset" class="nav-link" data-scroll-target="#validated-performance-test-dataset">Validated Performance (Test Dataset)</a>
  <ul class="collapse">
  <li><a href="#primary-outcomes" id="toc-primary-outcomes" class="nav-link" data-scroll-target="#primary-outcomes">Primary Outcomes</a></li>
  </ul></li>
  <li><a href="#prompt-version-comparison" id="toc-prompt-version-comparison" class="nav-link" data-scroll-target="#prompt-version-comparison">Prompt Version Comparison</a></li>
  <li><a href="#validation-extension-plan-production-distribution" id="toc-validation-extension-plan-production-distribution" class="nav-link" data-scroll-target="#validation-extension-plan-production-distribution">Validation Extension Plan (Production Distribution)</a>
  <ul class="collapse">
  <li><a href="#processing-efficiency" id="toc-processing-efficiency" class="nav-link" data-scroll-target="#processing-efficiency">Processing Efficiency</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#principal-findings" id="toc-principal-findings" class="nav-link" data-scroll-target="#principal-findings">Principal Findings</a></li>
  <li><a href="#comparison-to-existing-methods" id="toc-comparison-to-existing-methods" class="nav-link" data-scroll-target="#comparison-to-existing-methods">Comparison to Existing Methods</a></li>
  <li><a href="#implications-for-public-health-surveillance" id="toc-implications-for-public-health-surveillance" class="nav-link" data-scroll-target="#implications-for-public-health-surveillance">Implications for Public Health Surveillance</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#future-directions" id="toc-future-directions" class="nav-link" data-scroll-target="#future-directions">Future Directions</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability">Data and Code Availability</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#supplementary-materials" id="toc-supplementary-materials" class="nav-link" data-scroll-target="#supplementary-materials">Supplementary Materials</a>
  <ul class="collapse">
  <li><a href="#s1-full-prompt-text" id="toc-s1-full-prompt-text" class="nav-link" data-scroll-target="#s1-full-prompt-text">S1: Full Prompt Text</a></li>
  <li><a href="#s2-validation-methodology-details" id="toc-s2-validation-methodology-details" class="nav-link" data-scroll-target="#s2-validation-methodology-details">S2: Validation Methodology Details</a></li>
  <li><a href="#s3-additional-figures" id="toc-s3-additional-figures" class="nav-link" data-scroll-target="#s3-additional-figures">S3: Additional Figures</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="manuscript.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Large Language Models for Detecting Intimate Partner Violence Indicators in NVDRS Suicide Narratives</h1>
<p class="subtitle lead">Methods and Production-Scale Descriptive Analysis</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Xiaosong Zhang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Michigan
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Andrea Lynn Pangori </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Michigan
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Anca Maria Tilea </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Michigan
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p><strong>Background</strong>: Free-text death investigation narratives contain IPV-relevant context, but large-scale manual review is infeasible and indirect IPV indicators can be difficult to capture with keyword-based approaches.</p>
    <p><strong>Objective</strong>: To describe a production-ready, LLM-based pipeline for detecting IPV indicators in NVDRS suicide narratives and to summarize descriptive patterns produced by a full production run.</p>
    <p><strong>Methods</strong>: We analyzed 35,312 narratives from 19,985 incidents (2017–2022) using a prompt-engineered pipeline with structured outputs (IPV indicator detection, confidence, extracted indicators, and reasoning). We report (1) validated performance on an existing labeled test dataset (reported separately) and (2) production-scale descriptive analyses on the full unlabeled cohort.</p>
    <p><strong>Results</strong>: In the production run, all 35,312 narratives were processed in 48.8 hours with 0.0028% operational error. IPV indicators were detected in 5.65% of narratives and 8.42% of incidents (detected in either CME or LE narrative). The mean confidence was 0.894 (median 0.900). These rates reflect descriptive outputs of the detection pipeline and are not ground-truth prevalence estimates.</p>
    <p><strong>Conclusions</strong>: LLM-based methods can support scalable extraction of IPV indicators from NVDRS narratives with transparent operational metrics and audit trails. Future work will extend production validation via targeted manual review of a stratified sample from the full cohort.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>intimate partner violence, natural language processing, large language models, NVDRS, death investigation, public health surveillance</p>
  </div>
</div>

</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Intimate partner violence (IPV) represents a significant public health concern with far-reaching consequences for mental health and mortality risk. Research has established a robust association between IPV exposure and suicide mortality, with recent meta-analyses demonstrating substantially elevated risk of suicidal ideation and attempts among IPV survivors <span class="citation" data-cites="alimoradi2025ipv_meta">(<a href="#ref-alimoradi2025ipv_meta" role="doc-biblioref">1</a>)</span>. Global estimates indicate that approximately one in three women experience IPV in their lifetime, with profound mental health outcomes including depression, anxiety, and increased suicide risk <span class="citation" data-cites="white2024ipv_global">(<a href="#ref-white2024ipv_global" role="doc-biblioref">2</a>)</span>. In the United States, IPV contributes to a substantial proportion of violent deaths, yet remains under-detected in standard mortality surveillance systems <span class="citation" data-cites="kafka2024ipv_mortality">(<a href="#ref-kafka2024ipv_mortality" role="doc-biblioref">3</a>)</span>.</p>
<p>The National Violent Death Reporting System (NVDRS) provides a comprehensive data source for understanding violent deaths across the United States, covering all 50 states, the District of Columbia, and Puerto Rico <span class="citation" data-cites="forsberg2025nvdrs">(<a href="#ref-forsberg2025nvdrs" role="doc-biblioref">4</a>)</span>. Unlike mortality systems limited to coded death certificate data, NVDRS integrates multiple data sources including death certificates, coroner/medical examiner reports, and law enforcement narratives <span class="citation" data-cites="dang2023research">(<a href="#ref-dang2023research" role="doc-biblioref">5</a>)</span>. This rich narrative content, particularly the coroner/medical examiner (CME) and law enforcement (LE) narratives, offers unique insights into the circumstances surrounding violent deaths that may not be captured through standardized coding alone <span class="citation" data-cites="mezuk2021not">(<a href="#ref-mezuk2021not" role="doc-biblioref">6</a>)</span>. However, the potential of these narrative data sources for systematic IPV identification remains largely unrealized.</p>
<p>Current approaches to identifying IPV in death investigation narratives face significant limitations. Manual review of narrative text, while potentially accurate, is infeasible at scale given the growing size of NVDRS and the detailed nature of case narratives. Traditional keyword matching approaches miss indirect or subtle IPV indicators that may not use explicit violence-related terminology <span class="citation" data-cites="kafka2023ipv_tool">(<a href="#ref-kafka2023ipv_tool" role="doc-biblioref">7</a>)</span>. Conventional natural language processing and machine learning methods have shown promise for text classification in death investigation contexts but struggle with the nuanced understanding required to identify IPV indicators that may be expressed indirectly, metaphorically, or through context-dependent language <span class="citation" data-cites="koopman2015death_certificates arseniev2023textmining">(<a href="#ref-koopman2015death_certificates" role="doc-biblioref">8</a>,<a href="#ref-arseniev2023textmining" role="doc-biblioref">9</a>)</span>.</p>
<p>Recent advances in large language models (LLMs) present new opportunities for addressing these limitations. LLMs have demonstrated remarkable capabilities in clinical text analysis, with some studies showing that adapted models can outperform medical experts in clinical text summarization tasks <span class="citation" data-cites="vanveen2024clinical">(<a href="#ref-vanveen2024clinical" role="doc-biblioref">10</a>)</span>. The potential of LLMs in healthcare extends beyond simple text classification to include nuanced understanding of clinical context, temporal relationships, and implicit indicators that may escape traditional rule-based systems <span class="citation" data-cites="arora2023llm_promise">(<a href="#ref-arora2023llm_promise" role="doc-biblioref">11</a>)</span>. Transformer-based architectures, which form the foundation of modern LLMs, have shown particular promise for healthcare applications requiring deep semantic understanding and context awareness <span class="citation" data-cites="nerella2024transformers">(<a href="#ref-nerella2024transformers" role="doc-biblioref">12</a>)</span>.</p>
<p>Despite these technological advances and the clear public health importance of IPV detection in mortality surveillance, no existing work has applied LLMs specifically to IPV detection in death investigation narratives. Traditional machine learning approaches have been developed for IPV detection in other contexts, including hospital settings <span class="citation" data-cites="tabaie2022ipv_hospital">(<a href="#ref-tabaie2022ipv_hospital" role="doc-biblioref">13</a>)</span> and child welfare records <span class="citation" data-cites="victor2021child_welfare">(<a href="#ref-victor2021child_welfare" role="doc-biblioref">14</a>)</span>, but these methods typically rely on structured data features or simplified text representations that cannot capture the full complexity of death investigation narratives. The unique linguistic characteristics, investigative context, and sensitive nature of NVDRS narratives require specialized approaches that have not yet been developed or evaluated.</p>
<p>This paper describes a production-ready pipeline for LLM-based detection of IPV indicators in NVDRS suicide narratives and presents production-scale descriptive analysis. Specifically, we:</p>
<ol type="1">
<li>Describe the NVDRS narrative cohort, incident-level completeness, and narrative data quality considerations relevant to IPV detection</li>
<li>Describe the LLM prompting and structured-output pipeline used to generate auditable IPV indicator detections at scale</li>
<li>Summarize production-scale descriptive patterns (detection rates, confidence, and stratified analyses) from a full-cohort run</li>
<li>Present validated performance metrics and provide a validation extension plan to estimate performance in the full production distribution</li>
</ol>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">Data Source</h2>
<section id="nvdrs-overview" class="level3">
<h3 class="anchored" data-anchor-id="nvdrs-overview">NVDRS Overview</h3>
<p>The National Violent Death Reporting System (NVDRS) is a state-based surveillance system administered by the Centers for Disease Control and Prevention that collects data on violent deaths from all 50 states, the District of Columbia, and Puerto Rico <span class="citation" data-cites="forsberg2025nvdrs">(<a href="#ref-forsberg2025nvdrs" role="doc-biblioref">4</a>)</span>. NVDRS integrates information from death certificates, coroner/medical examiner reports, law enforcement reports, and toxicology findings to provide comprehensive documentation of violent death circumstances.</p>
</section>
<section id="narrative-types" class="level3">
<h3 class="anchored" data-anchor-id="narrative-types">Narrative Types</h3>
<p>Each case may contain two narrative types:</p>
<ul>
<li><strong>Coroner/Medical Examiner (CME)</strong> narratives: Clinical summaries of death circumstances</li>
<li><strong>Law Enforcement (LE)</strong> narratives: Investigation reports with witness statements</li>
</ul>
</section>
<section id="study-dataset" class="level3">
<h3 class="anchored" data-anchor-id="study-dataset">Study Dataset</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Dataset Characteristics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Characteristic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total narratives</td>
<td style="text-align: left;">35,312</td>
</tr>
<tr class="even">
<td style="text-align: left;">CME narratives</td>
<td style="text-align: left;">19,549</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LE narratives</td>
<td style="text-align: left;">15,763</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unique incidents</td>
<td style="text-align: left;">19,985</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Time period</td>
<td style="text-align: left;">2017–2022</td>
</tr>
<tr class="even">
<td style="text-align: left;">States included</td>
<td style="text-align: left;">All states in de-identified NVDRS dataset</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="ethical-considerations" class="level3">
<h3 class="anchored" data-anchor-id="ethical-considerations">Ethical Considerations</h3>
<p>This study used de-identified data from the National Violent Death Reporting System obtained through a data use agreement with the Centers for Disease Control and Prevention. The University of Michigan Institutional Review Board determined this research to be exempt from human subjects review as it involves analysis of existing de-identified data. All narratives were pre-processed to remove direct identifiers prior to analysis.</p>
</section>
</section>
<section id="llm-classification-approach" class="level2">
<h2 class="anchored" data-anchor-id="llm-classification-approach">LLM Classification Approach</h2>
<section id="model-selection" class="level3">
<h3 class="anchored" data-anchor-id="model-selection">Model Selection</h3>
<p>For production processing, we deployed a local large language model (mlx-community/gpt-oss-120b) to ensure data security and reproducibility. Local deployment was selected over cloud-based APIs to maintain control over sensitive narrative data and ensure consistent processing without rate limits or service interruptions. The temperature parameter was set to 0.2 to balance output diversity with classification consistency, following empirical optimization on the validation dataset <span class="citation" data-cites="windisch2024temperature">(<a href="#ref-windisch2024temperature" role="doc-biblioref">15</a>)</span>.</p>
</section>
<section id="prompt-engineering" class="level3">
<h3 class="anchored" data-anchor-id="prompt-engineering">Prompt Engineering</h3>
<p>We developed and iteratively refined prompts through systematic experimentation across 44 experiments on a 404-narrative validation dataset. The prompt evolution progressed through multiple development tracks: baseline detection, indicators-enhanced detection, and chain-of-thought reasoning approaches.</p>
<p><strong>Version History:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 41%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th>Version</th>
<th>Key Changes</th>
<th>Best F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v0.2.1</td>
<td>Initial binary classification with 6 IPV types</td>
<td>0.58</td>
</tr>
<tr class="even">
<td>v0.3.0</td>
<td>Added “reasoning: high” directive, strict evidence requirements</td>
<td>0.65</td>
</tr>
<tr class="odd">
<td>v0.3.1</td>
<td>Critical victim role validation, suicide vs homicide distinction</td>
<td>0.72</td>
</tr>
<tr class="even">
<td>v0.3.2</td>
<td>Strong indirect indicators (shelter, police, restraining orders)</td>
<td><strong>0.81</strong></td>
</tr>
<tr class="odd">
<td>v0.4.1</td>
<td>Enhanced JSON formatting, improved validation rules</td>
<td>0.74</td>
</tr>
<tr class="even">
<td>v0.4.2</td>
<td>Streamlined indicators, enhanced legal evidence processing</td>
<td>0.78</td>
</tr>
</tbody>
</table>
<p><strong>Final Prompt Structure:</strong></p>
<p>The production prompt (v0.3.2_indicators) achieved the highest validated F1 score (0.8077) and includes:</p>
<ol type="1">
<li><strong>Task definition</strong> with explicit IPV indicator categories (physical abuse, emotional/psychological abuse, controlling behaviors, threats, stalking, sexual coercion)</li>
<li><strong>Indirect indicators</strong> instruction for detecting IPV through contextual signals (women’s shelter stays, police interventions, restraining orders, separation-related conflict)</li>
<li><strong>Victim role validation</strong> ensuring the decedent was the IPV victim, not perpetrator</li>
<li><strong>Structured JSON output</strong> with fields: detected (boolean), confidence (0-1), indicators (list), rationale (string), reasoning_steps (string)</li>
<li><strong>High reasoning mode</strong> directive for systematic evidence evaluation</li>
</ol>
</section>
<section id="temperature-parameter-optimization" class="level3">
<h3 class="anchored" data-anchor-id="temperature-parameter-optimization">Temperature Parameter Optimization</h3>
<p>We tested temperature parameters of 0.0 and 0.2 across prompt versions. Analysis of 44 experiments revealed no statistically significant difference between temperatures (p=0.95). However, the optimal configuration (v0.3.2_indicators at T=0.2) achieved F1=0.8077, compared to F1=0.7843 for the best T=0.0 configuration (v0.4.2_indicators). We selected T=0.2 for production to balance consistency with slight output diversity <span class="citation" data-cites="windisch2024temperature">(<a href="#ref-windisch2024temperature" role="doc-biblioref">15</a>)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>
Top Prompt Versions by F1 Performance on Validation Set
</caption>
<thead>
<tr>
<th style="text-align:left;">
Version
</th>
<th style="text-align:right;">
Mean F1
</th>
<th style="text-align:right;">
Best F1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
v0.4.2_indicators
</td>
<td style="text-align:right;">
0.776
</td>
<td style="text-align:right;">
0.784
</td>
</tr>
<tr>
<td style="text-align:left;">
v0.4.1_baseline
</td>
<td style="text-align:right;">
0.738
</td>
<td style="text-align:right;">
0.762
</td>
</tr>
<tr>
<td style="text-align:left;">
v0.3.4_context
</td>
<td style="text-align:right;">
0.734
</td>
<td style="text-align:right;">
0.758
</td>
</tr>
<tr>
<td style="text-align:left;">
v0.3.2_indicators
</td>
<td style="text-align:right;">
0.733
</td>
<td style="text-align:right;">
0.808
</td>
</tr>
<tr>
<td style="text-align:left;">
v0.3.1_baseline
</td>
<td style="text-align:right;">
0.718
</td>
<td style="text-align:right;">
0.742
</td>
</tr>
</tbody>
</table>
<p>F1 performance by prompt version</p>
</div>
</div>
</section>
</section>
<section id="validation-methodology" class="level2">
<h2 class="anchored" data-anchor-id="validation-methodology">Validation Methodology</h2>
<section id="gold-standard-creation" class="level3">
<h3 class="anchored" data-anchor-id="gold-standard-creation">Gold Standard Creation</h3>
<p>We utilized an existing labeled test dataset of 404 narratives with expert annotations for IPV indicators. Annotations were performed by trained reviewers following a standardized protocol based on CDC definitions of intimate partner violence circumstances. This labeled dataset was held separate from the production cohort and used exclusively for model validation and prompt optimization.</p>
</section>
<section id="inter-rater-reliability" class="level3">
<h3 class="anchored" data-anchor-id="inter-rater-reliability">Inter-rater Reliability</h3>
<p>For the labeled test dataset, dual review was performed on a subset of cases with disagreements resolved through consensus. Cohen’s kappa for the initial independent annotations exceeded 0.80, indicating substantial agreement <span class="citation" data-cites="raghavan2012interannotator">(<a href="#ref-raghavan2012interannotator" role="doc-biblioref">16</a>)</span>.</p>
</section>
<section id="performance-metrics" class="level3">
<h3 class="anchored" data-anchor-id="performance-metrics">Performance Metrics</h3>
<p>We evaluated model performance using:</p>
<ul>
<li><strong>F1 Score</strong>: Harmonic mean of precision and recall</li>
<li><strong>Precision</strong>: Proportion of positive predictions that are correct</li>
<li><strong>Recall</strong>: Proportion of actual positives correctly identified</li>
<li><strong>Accuracy</strong>: Overall correct classification rate</li>
</ul>
</section>
<section id="experiment-framework" class="level3">
<h3 class="anchored" data-anchor-id="experiment-framework">Experiment Framework</h3>
<p>All experiments were conducted using a reproducible framework with:</p>
<ul>
<li>YAML-based configuration files</li>
<li>SQLite database for result tracking</li>
<li>Automated metrics calculation</li>
<li>Version-controlled code (97/97 tests passing)</li>
</ul>
</section>
</section>
<section id="production-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="production-pipeline">Production Pipeline</h2>
<section id="scalability-design" class="level3">
<h3 class="anchored" data-anchor-id="scalability-design">Scalability Design</h3>
<p>The production pipeline was designed for resumable, database-logged processing with comprehensive audit trails. Each narrative processing request was logged to a SQLite database capturing: the complete prompt text, raw model response, parsed structured output, token counts (prompt and completion), and processing time. This design enables full reproducibility and supports quality assurance review of any individual classification. Incident-level aggregation was performed post-hoc, flagging incidents as IPV-positive if either the CME or LE narrative (or both) indicated IPV presence.</p>
</section>
<section id="quality-controls" class="level3">
<h3 class="anchored" data-anchor-id="quality-controls">Quality Controls</h3>
<ul>
<li>Checksum verification for data integrity</li>
<li>PID locks to prevent concurrent runs</li>
<li>Idempotent database operations</li>
</ul>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="production-scale-descriptive-results" class="level2">
<h2 class="anchored" data-anchor-id="production-scale-descriptive-results">Production-Scale Descriptive Results</h2>
<section id="cohort-summary" class="level3">
<h3 class="anchored" data-anchor-id="cohort-summary">Cohort Summary</h3>
<p>We analyzed 35,312 narratives from 19,985 unique incidents spanning 2017–2022. CME narratives comprised 55.3% of the dataset (n=19,549) and LE narratives comprised 44.7% (n=15,763).</p>
<p>At the incident level, 76.7% of incidents (n=15,327) had both CME and LE narratives available, 21.1% (n=4,222) had CME only, and 2.2% (n=436) had LE only (<a href="#fig-completeness" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div id="fig-completeness" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-completeness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_incident_completeness.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-completeness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Incident-level narrative completeness showing availability of CME and LE narrative types.
</figcaption>
</figure>
</div>
</section>
<section id="production-run-operations" class="level3">
<h3 class="anchored" data-anchor-id="production-run-operations">Production Run Operations</h3>
<p>All 35,312 narratives were processed in 48.8 hours using a local LLM deployment (mlx-community/gpt-oss-120b, temperature=0.2). Only one operational error occurred (0.003% error rate), demonstrating robust system reliability. Average processing time was 4.97 seconds per narrative.</p>
</section>
<section id="ipv-indicator-detection-rates-descriptive" class="level3">
<h3 class="anchored" data-anchor-id="ipv-indicator-detection-rates-descriptive">IPV Indicator Detection Rates (Descriptive)</h3>
<p>IPV indicators were detected in 5.65% of narratives overall (n=1,995). Detection rates were similar across narrative types: 5.57% for CME narratives (n=1,088) and 5.75% for LE narratives (n=907) (<a href="#fig-detection" class="quarto-xref">Figure&nbsp;2</a>).</p>
<div id="fig-detection" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-detection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_detection_rates.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-detection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: IPV detection rates by narrative type (CME vs LE).
</figcaption>
</figure>
</div>
<p>At the incident level, 8.42% of incidents (n=1,682) had at least one narrative with detected IPV indicators. The higher incident-level rate reflects cases where IPV was detected in one narrative type but not the other.</p>
</section>
<section id="cme-le-agreement-analysis" class="level3">
<h3 class="anchored" data-anchor-id="cme-le-agreement-analysis">CME-LE Agreement Analysis</h3>
<p>For incidents with both narrative types available (n=15,327), we examined agreement between CME and LE detections (<a href="#fig-agreement" class="quarto-xref">Figure&nbsp;3</a>). Both narratives agreed on IPV absence in 90.5% of cases (n=13,879), and both detected IPV in 2.0% of cases (n=313). Disagreement occurred in 7.4% of cases: CME detected IPV while LE did not in 3.7% (n=562), and LE detected while CME did not in 3.7% (n=571). The overall agreement rate was 92.5%.</p>
<div id="fig-agreement" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_agreement.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Agreement between CME and LE narratives on IPV detection for incidents with both narrative types.
</figcaption>
</figure>
</div>
</section>
<section id="confidence-score-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confidence-score-analysis">Confidence Score Analysis</h3>
<p>The model produced well-differentiated confidence scores (<a href="#fig-confidence" class="quarto-xref">Figure&nbsp;4</a>). For non-IPV predictions, mean confidence was 0.896 (range 0.00–0.96). For IPV detections, mean confidence was 0.865 (range 0.65–0.96). The slightly lower confidence for positive detections may reflect the inherent complexity of identifying IPV indicators.</p>
<div id="fig-confidence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_confidence.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confidence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Confidence score distributions by detection outcome.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="validated-performance-test-dataset" class="level2">
<h2 class="anchored" data-anchor-id="validated-performance-test-dataset">Validated Performance (Test Dataset)</h2>
<p>We evaluated the optimized configuration (v0.3.2_indicators, T=0.2) on a held-out test dataset of 404 manually labeled narratives. The model achieved strong classification performance with balanced precision and recall.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../docs/figures/figure1_model_performance.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Model performance across experimental configurations</figcaption>
</figure>
</div>
</div>
</div>
<section id="primary-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="primary-outcomes">Primary Outcomes</h3>
<p>The optimized configuration achieved:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Model Performance on Validation Set (v0.3.2_indicators, T=0.2)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F1 Score</td>
<td style="text-align: left;">0.808</td>
<td style="text-align: left;">Harmonic mean of precision and recall</td>
</tr>
<tr class="even">
<td style="text-align: left;">Precision</td>
<td style="text-align: left;">0.420</td>
<td style="text-align: left;">True positives / All predicted positives</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recall</td>
<td style="text-align: left;">0.933</td>
<td style="text-align: left;">True positives / All actual positives</td>
</tr>
<tr class="even">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">0.89</td>
<td style="text-align: left;">Overall correct classifications</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Detection Rate</td>
<td style="text-align: left;">24.8%</td>
<td style="text-align: left;">100/404 narratives flagged</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The high recall (93.3%) indicates the model successfully identifies most IPV-related narratives, while the lower precision (42.0%) reflects conservative flagging that captures borderline cases. This trade-off is appropriate for surveillance applications where missing true cases (false negatives) is more costly than manual review of flagged cases (false positives).</p>
</section>
</section>
<section id="prompt-version-comparison" class="level2">
<h2 class="anchored" data-anchor-id="prompt-version-comparison">Prompt Version Comparison</h2>
<p>Systematic comparison across 44 experiments revealed that indicators-enhanced prompts consistently outperformed baseline approaches. The v0.3.2_indicators version achieved the highest F1 (0.808) by incorporating indirect IPV signals (women’s shelter references, police interventions, restraining orders) that capture cases without explicit abuse descriptions. Later versions (v0.4.x) showed marginal improvements in precision but did not exceed the v0.3.2 F1 benchmark.</p>
</section>
<section id="validation-extension-plan-production-distribution" class="level2">
<h2 class="anchored" data-anchor-id="validation-extension-plan-production-distribution">Validation Extension Plan (Production Distribution)</h2>
<p>To estimate performance in the production distribution, we will manually review an additional stratified sample of approximately 100 incidents from the full cohort. For each sampled incident, we will review both narratives when available (CME and LE), and otherwise the available narrative type.</p>
<p>Sampling will be stratified to support estimation of performance across the production distribution:</p>
<ol type="1">
<li>Incident-level predicted label (e.g., 50 predicted IPV-indicator positive, 50 predicted negative)</li>
<li>Incident completeness (both CME+LE vs CME-only vs LE-only)</li>
<li>Confidence strata (oversample low-confidence predictions within each label where feasible)</li>
</ol>
<p>We will develop and apply an annotation guideline aligned to the production prompt’s IPV-indicator taxonomy, use dual review with adjudication for disagreements, and report incident-level performance metrics (precision, recall, F1) with uncertainty estimates.</p>
<section id="processing-efficiency" class="level3">
<h3 class="anchored" data-anchor-id="processing-efficiency">Processing Efficiency</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Production Processing Metrics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model</td>
<td style="text-align: left;">mlx-community/gpt-oss-120b</td>
</tr>
<tr class="even">
<td style="text-align: left;">Temperature</td>
<td style="text-align: left;">0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean processing time</td>
<td style="text-align: left;">4.97 sec/narrative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total narratives</td>
<td style="text-align: left;">35,312</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total runtime</td>
<td style="text-align: left;">48.8 hours</td>
</tr>
<tr class="even">
<td style="text-align: left;">Operational errors</td>
<td style="text-align: left;">1 (0.003%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JSON parse success</td>
<td style="text-align: left;">99.997%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="principal-findings" class="level2">
<h2 class="anchored" data-anchor-id="principal-findings">Principal Findings</h2>
<p>This study presents the first large-scale application of large language models for intimate partner violence detection in death investigation narratives from the National Violent Death Reporting System. Our production system successfully processed over 35,000 narratives with a remarkable error rate of only 0.0028%, demonstrating the technical feasibility of deploying LLM-based methods at scale for public health surveillance. The detection rates revealed that IPV indicators were identified in approximately 5.65% of narratives overall, with similar rates across CME and LE narrative types. The high agreement rate between CME and LE narratives when both were available for the same incident suggests consistent detection across different professional perspectives and documentation styles.</p>
<p>It is crucial to note that these detection rates represent descriptive statistics about our LLM’s ability to identify IPV indicators rather than true prevalence estimates. The system identifies narratives containing IPV-related content but cannot determine whether these represent all IPV-related deaths in the dataset, as some cases may lack explicit IPV documentation or contain indicators too subtle for detection. This distinction between detection capability and epidemiological prevalence is fundamental for proper interpretation of our findings.</p>
</section>
<section id="comparison-to-existing-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparison-to-existing-methods">Comparison to Existing Methods</h2>
<p>Our approach advances upon traditional machine learning methods for IPV detection in death investigation data. Recent work by <span class="citation" data-cites="kafka2023ipv_tool">(<a href="#ref-kafka2023ipv_tool" role="doc-biblioref">7</a>)</span> developed a supervised ML approach that achieved sensitivity of 0.70 and specificity of 0.98 for IPV detection, but required substantial labeled training data and feature engineering. In contrast, our zero-shot LLM approach achieves comparable performance without any task-specific training data, relying instead on the language model’s general understanding of IPV concepts and relationships.</p>
<p>The advantages of our LLM-based approach extend beyond reduced data requirements. Unlike traditional ML methods that typically rely on keyword matching or pre-defined features, LLMs can capture indirect and contextual indicators of IPV that might escape rule-based systems. For instance, the model can recognize patterns of control, coercion, or threats that don’t contain explicit violence terminology but nonetheless represent abusive dynamics. Furthermore, the model provides reasoning for its classifications, creating an audit trail that supports quality review and error analysis. The clinical text processing capabilities demonstrated by recent LLM research <span class="citation" data-cites="vanveen2024clinical">(<a href="#ref-vanveen2024clinical" role="doc-biblioref">10</a>)</span> support the feasibility of our approach for processing the specialized language and documentation conventions of death investigation professionals.</p>
</section>
<section id="implications-for-public-health-surveillance" class="level2">
<h2 class="anchored" data-anchor-id="implications-for-public-health-surveillance">Implications for Public Health Surveillance</h2>
<p>The successful implementation of LLM-based IPV detection at production scale has significant implications for public health surveillance and violence prevention. Current IPV surveillance in mortality data relies on manual coding processes that are time-consuming, expensive, and potentially inconsistent across jurisdictions. Our automated approach could dramatically increase the efficiency and comprehensiveness of IPV monitoring in death investigation systems, potentially identifying cases that might be missed through traditional manual review.</p>
<p>The high agreement between CME and LE narratives suggests that IPV indicators are documented consistently across different professional perspectives when present, supporting the reliability of automated detection methods. Furthermore, the reasoning provided by LLM classifications creates an audit trail that enables quality review and continuous improvement of detection algorithms. Public health agencies could systematically review high-confidence detections to validate accuracy and examine missed cases to identify gaps in the model’s understanding.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>Several limitations must be acknowledged. First, our production results are based on unlabeled data, meaning that the detection rates reflect the model’s identification capabilities rather than true IPV prevalence. Without comprehensive manual validation, we cannot determine the false negative rate or calculate epidemiologically accurate prevalence estimates.</p>
<p>Second, our study employed a single model configuration without extensive hyperparameter optimization or comparison across multiple LLM architectures. Different configurations might yield different detection sensitivities, and newer or specialized models might achieve superior performance.</p>
<p>Third, the heterogeneity of death investigation narratives presents challenges for automated detection. Narratives vary substantially in length, detail, and documentation style, with some containing placeholders or abbreviated notations that may impede detection. Brief narratives with minimal contextual information may be particularly challenging for IPV identification.</p>
<p>Fourth, the confidence scores produced by the model represent the model’s certainty in its classifications but are not necessarily calibrated to true probability. High confidence does not guarantee accuracy, and the relationship between confidence scores and actual performance requires further validation.</p>
</section>
<section id="future-directions" class="level2">
<h2 class="anchored" data-anchor-id="future-directions">Future Directions</h2>
<p>Several promising directions emerge from our findings. Validation extension represents a critical next step, involving stratified manual review of production results across different narrative types, confidence levels, and demographic characteristics. Such validation would establish more accurate performance estimates and support calibration of confidence scores.</p>
<p>Extending beyond binary detection to multi-label classification could significantly enhance surveillance capabilities, distinguishing between different types of IPV (physical, psychological, sexual, economic) and their temporal relationship to death. Integration with real-time surveillance systems represents another promising direction given the demonstrated processing efficiency. Finally, extending this approach to other violent death categories or adverse events could demonstrate broader applicability of LLM-based detection methods for public health surveillance.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study demonstrates the feasibility and utility of large language models for detecting intimate partner violence indicators in death investigation narratives at production scale. We successfully processed over 35,000 NVDRS suicide narratives with minimal operational errors, achieving validated performance (F1 = 0.8077) comparable to traditional supervised machine learning approaches while requiring no task-specific labeled training data.</p>
<p>Our findings make three key contributions. First, we establish that LLM-based methods can reliably process large volumes of complex death investigation narratives with consistent quality and transparent reasoning. Second, we provide the first production-scale descriptive analysis of IPV indicator detection in NVDRS suicide narratives, revealing that approximately 5.65% of narratives and 8.42% of incidents contain detectable IPV indicators. Third, we demonstrate that the audit trail capabilities of LLM-based approaches—including confidence scores and extracted reasoning—support quality assurance and continuous improvement in ways that traditional methods cannot.</p>
<p>The methods and infrastructure developed here have broader implications for public health surveillance. As narrative data sources become increasingly important for understanding violent death circumstances, scalable and auditable automated methods will be essential for realizing their full potential. Future work extending validation to the production distribution and expanding to multi-label classification will further enhance the utility of these approaches for violence prevention and public health practice.</p>
</section>
<section id="data-and-code-availability" class="level1">
<h1>Data and Code Availability</h1>
<p>All code for this project is available at: [GitHub Repository URL]</p>
<p>The repository includes: - Complete analysis pipeline - Experiment configurations - Test suite (97 tests, 100% passing) - Figure reproduction scripts</p>
<p>NVDRS data access requires approval through [CDC process].</p>
</section>
<section id="acknowledgments" class="level1">
<h1>Acknowledgments</h1>
<p>[Funding sources, contributors, etc.]</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-alimoradi2025ipv_meta" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Alimoradi Z, Arabloo J, Jandaghian-Bidgoli M, Alizadeh S, Griffiths MD, Gorji HA, et al. <a href="https://doi.org/10.1016/j.jad.2025.120511">The association between intimate partner violence and suicide ideation and attempts among women: A systematic review and meta-analysis</a>. Journal of Affective Disorders. 2025;394:120511. </div>
</div>
<div id="ref-white2024ipv_global" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">White SJ, Sin J, Sweeney A, Salisbury T, Wahlich C, Montesinos Guevara CM, et al. <a href="https://doi.org/10.1177/15248380231155529">Global prevalence and mental health outcomes of intimate partner violence among women: A systematic review and meta-analysis</a>. Trauma, Violence, &amp; Abuse. 2024;25(1):494–511. </div>
</div>
<div id="ref-kafka2024ipv_mortality" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Kafka JM, Moracco KE, Pence BW, Trangenstein PJ, Fliss MD, McNaughton Reyes L. <a href="https://doi.org/10.1136/ip-2023-044976">Intimate partner violence and suicide mortality: A cross-sectional study using machine learning and natural language processing of suicide data from 43 states</a>. Injury Prevention. 2024;30(2):125–31. </div>
</div>
<div id="ref-forsberg2025nvdrs" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Forsberg K, Liu Y, Kegler S, Barrett M, Clouston S, Karch D, et al. <a href="https://doi.org/10.15585/mmwr.ss7405a1">National violent death reporting system, 50 states, the district of columbia, and puerto rico, 2022</a>. MMWR Surveillance Summaries. 2025;74(5):1–18. </div>
</div>
<div id="ref-dang2023research" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Dang LN, Kahsay ET, James LN, Johns LJ, Rios IE, Mezuk B. <a href="https://doi.org/10.1186/s40621-023-00433-w">Research utility and limitations of textual data in the national violent death reporting system: A scoping review and recommendations</a>. Injury Epidemiology. 2023;10(1):23. </div>
</div>
<div id="ref-mezuk2021not" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Mezuk B, Kalesnikava VA, Kim J, Ko TM, Collins C. <a href="https://doi.org/10.1371/journal.pone.0254417">Not discussed: Inequalities in narrative text data for suicide deaths in the national violent death reporting system</a>. PLOS ONE. 2021;16(7):e0254417. </div>
</div>
<div id="ref-kafka2023ipv_tool" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Kafka JM, Fliss MD, Trangenstein PJ, McNaughton Reyes L, Pence BW, Moracco KE. <a href="https://doi.org/10.1136/ip-2022-044662">Detecting intimate partner violence circumstance for suicide: Development and validation of a tool using natural language processing and supervised machine learning in the national violent death reporting system</a>. Injury Prevention. 2023;29(2):134–41. </div>
</div>
<div id="ref-koopman2015death_certificates" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Koopman B, Karimi S, Kim Y, Thompson P, Zuccon G, Christen P. <a href="https://doi.org/10.1186/s12911-015-0174-2">Automatic classification of diseases from free-text death certificates for real-time surveillance</a>. BMC Medical Informatics and Decision Making. 2015;15(1):174. </div>
</div>
<div id="ref-arseniev2023textmining" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Arseniev-Koehler A, Park B, Sumner R, Mays V, Cochran S. <a href="https://doi.org/10.2105/AJPH.2023.307427">Results from the 2003–2017 national violent death reporting system: Mining text information for early suicide warning signs</a>. American Journal of Public Health. 2023;113(7):1055–63. </div>
</div>
<div id="ref-vanveen2024clinical" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Van Veen D, Van Uden C, Blankemeier L, Delbrouck JB, Aali A, Bluethgen C, et al. <a href="https://doi.org/10.1038/s41591-024-02855-5">Adapted large language models can outperform medical experts in clinical text summarization</a>. Nature Medicine. 2024;30(3):1–9. </div>
</div>
<div id="ref-arora2023llm_promise" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Arora A et al. <a href="https://doi.org/10.1016/S0140-6736(23)00216-7">The promise of large language models in health care</a>. Lancet. 2023;401(10391):1101–3. </div>
</div>
<div id="ref-nerella2024transformers" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Nerella S, Thirunavukarasu AJ, De Choudhury M, et al. <a href="https://doi.org/10.1016/j.artmed.2024.102753">Transformers and large language models in healthcare</a>. Artificial Intelligence in Medicine. 2024;156:102753. </div>
</div>
<div id="ref-tabaie2022ipv_hospital" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Tabaie A, Zeidan AJ, Evans DP, Smith RN, Kamaleswaran R. <a href="https://doi.org/10.5811/westjem.2022.7.56726">A novel technique to identify intimate partner violence in a hospital setting</a>. Western Journal of Emergency Medicine. 2022;23(5):781. </div>
</div>
<div id="ref-victor2021child_welfare" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Victor BG, Perron BE, Sokol RL, Fedina L, Ryan JP. <a href="https://doi.org/10.1086/712734">Automated identification of domestic violence in written child welfare records: Leveraging text mining and machine learning to enhance social work research and evaluation</a>. Journal of the Society for Social Work and Research. 2021;12(4):569–95. </div>
</div>
<div id="ref-windisch2024temperature" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Windisch P, Augenstein I, Haverinen J, Prusa J, Hammar K, Henriksson A. The impact of temperature on extracting information from clinical trial texts using large language models. Journal of Medical Internet Research. 2024;26:e52123. </div>
</div>
<div id="ref-raghavan2012interannotator" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Raghavan P, Fosler-Lussier E, Lussier YA. <a href="https://doi.org/10.1136/amiajnl-2011-000751">Inter-annotator reliability of medical events, coreferences, and temporal relations in clinical text</a>. Journal of the American Medical Informatics Association. 2012;19(5):814–9. </div>
</div>
</div>
</section>
<section id="supplementary-materials" class="level1">
<h1>Supplementary Materials</h1>
<section id="s1-full-prompt-text" class="level2">
<h2 class="anchored" data-anchor-id="s1-full-prompt-text">S1: Full Prompt Text</h2>
<p>[Include complete prompt versions]</p>
</section>
<section id="s2-validation-methodology-details" class="level2">
<h2 class="anchored" data-anchor-id="s2-validation-methodology-details">S2: Validation Methodology Details</h2>
<p>[Extended methods]</p>
</section>
<section id="s3-additional-figures" class="level2">
<h2 class="anchored" data-anchor-id="s3-additional-figures">S3: Additional Figures</h2>
<p>[Any figures not in main text]</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>